import { ColorConfig } from "./types";

export interface ThemePreset {
  id: string;
  name: string;
  description: string;
  author?: string;
  tags: string[];
  light: Record<string, ColorConfig>;
  dark: Record<string, ColorConfig>;
}

/**
 * Popular theme presets
 */
export const themePresets: ThemePreset[] = [
  {
    id: "dracula",
    name: "Dracula",
    description: "",
    author: "Zeno Rocha",
    tags: ["dark", "purple", "popular"],
    light: {
      background: { hue: 231, saturation: 15, lightness: 18, alpha: 1 },
      foreground: { hue: 60, saturation: 30, lightness: 96, alpha: 1 },
      primary: { hue: 265, saturation: 89, lightness: 78, alpha: 1 },
      "primary-foreground": { hue: 0, saturation: 0, lightness: 0, alpha: 1 },
      secondary: { hue: 191, saturation: 97, lightness: 77, alpha: 1 },
      "secondary-foreground": { hue: 0, saturation: 0, lightness: 0, alpha: 1 },
      accent: { hue: 135, saturation: 94, lightness: 65, alpha: 1 },
      "accent-foreground": { hue: 0, saturation: 0, lightness: 0, alpha: 1 },
      card: { hue: 231, saturation: 15, lightness: 22, alpha: 1 },
      "card-foreground": { hue: 60, saturation: 30, lightness: 96, alpha: 1 },
      popover: { hue: 231, saturation: 15, lightness: 18, alpha: 1 },
      "popover-foreground": { hue: 60, saturation: 30, lightness: 96, alpha: 1 },
      muted: { hue: 232, saturation: 14, lightness: 31, alpha: 1 },
      "muted-foreground": { hue: 226, saturation: 64, lightness: 88, alpha: 1 },
      destructive: { hue: 0, saturation: 100, lightness: 67, alpha: 1 },
      "destructive-foreground": { hue: 0, saturation: 0, lightness: 100, alpha: 1 },
      border: { hue: 232, saturation: 14, lightness: 31, alpha: 1 },
      input: { hue: 232, saturation: 14, lightness: 31, alpha: 1 },
      ring: { hue: 265, saturation: 89, lightness: 78, alpha: 1 },
      success: { hue: 135, saturation: 94, lightness: 65, alpha: 1 },
      "success-foreground": { hue: 0, saturation: 0, lightness: 0, alpha: 1 },
      warning: { hue: 65, saturation: 92, lightness: 76, alpha: 1 },
      "warning-foreground": { hue: 0, saturation: 0, lightness: 0, alpha: 1 },
      info: { hue: 191, saturation: 97, lightness: 77, alpha: 1 },
      "info-foreground": { hue: 0, saturation: 0, lightness: 0, alpha: 1 },
      "chart-1": { hue: 265, saturation: 89, lightness: 78, alpha: 1 },
      "chart-2": { hue: 326, saturation: 100, lightness: 74, alpha: 1 },
      "chart-3": { hue: 135, saturation: 94, lightness: 65, alpha: 1 },
      "chart-4": { hue: 191, saturation: 97, lightness: 77, alpha: 1 },
      "chart-5": { hue: 65, saturation: 92, lightness: 76, alpha: 1 },
      sidebar: { hue: 231, saturation: 15, lightness: 20, alpha: 1 },
      "sidebar-foreground": { hue: 60, saturation: 30, lightness: 96, alpha: 1 },
      "sidebar-primary": { hue: 265, saturation: 89, lightness: 78, alpha: 1 },
      "sidebar-primary-foreground": { hue: 0, saturation: 0, lightness: 0, alpha: 1 },
      "sidebar-accent": { hue: 232, saturation: 14, lightness: 27, alpha: 1 },
      "sidebar-accent-foreground": { hue: 60, saturation: 30, lightness: 96, alpha: 1 },
      "sidebar-border": { hue: 232, saturation: 14, lightness: 31, alpha: 0.3 },
      "sidebar-ring": { hue: 265, saturation: 89, lightness: 78, alpha: 1 },
    },
    dark: {
      background: { hue: 231, saturation: 15, lightness: 18, alpha: 1 },
      foreground: { hue: 60, saturation: 30, lightness: 96, alpha: 1 },
      primary: { hue: 265, saturation: 89, lightness: 78, alpha: 1 },
      "primary-foreground": { hue: 0, saturation: 0, lightness: 0, alpha: 1 },
      secondary: { hue: 191, saturation: 97, lightness: 77, alpha: 1 },
      "secondary-foreground": { hue: 0, saturation: 0, lightness: 0, alpha: 1 },
      accent: { hue: 135, saturation: 94, lightness: 65, alpha: 1 },
      "accent-foreground": { hue: 0, saturation: 0, lightness: 0, alpha: 1 },
      card: { hue: 231, saturation: 15, lightness: 22, alpha: 1 },
      "card-foreground": { hue: 60, saturation: 30, lightness: 96, alpha: 1 },
      popover: { hue: 231, saturation: 15, lightness: 18, alpha: 1 },
      "popover-foreground": { hue: 60, saturation: 30, lightness: 96, alpha: 1 },
      muted: { hue: 232, saturation: 14, lightness: 31, alpha: 1 },
      "muted-foreground": { hue: 226, saturation: 64, lightness: 88, alpha: 1 },
      destructive: { hue: 0, saturation: 100, lightness: 67, alpha: 1 },
      "destructive-foreground": { hue: 0, saturation: 0, lightness: 100, alpha: 1 },
      border: { hue: 232, saturation: 14, lightness: 31, alpha: 1 },
      input: { hue: 232, saturation: 14, lightness: 31, alpha: 1 },
      ring: { hue: 265, saturation: 89, lightness: 78, alpha: 1 },
      success: { hue: 135, saturation: 94, lightness: 65, alpha: 1 },
      "success-foreground": { hue: 0, saturation: 0, lightness: 0, alpha: 1 },
      warning: { hue: 65, saturation: 92, lightness: 76, alpha: 1 },
      "warning-foreground": { hue: 0, saturation: 0, lightness: 0, alpha: 1 },
      info: { hue: 191, saturation: 97, lightness: 77, alpha: 1 },
      "info-foreground": { hue: 0, saturation: 0, lightness: 0, alpha: 1 },
      "chart-1": { hue: 265, saturation: 89, lightness: 78, alpha: 1 },
      "chart-2": { hue: 326, saturation: 100, lightness: 74, alpha: 1 },
      "chart-3": { hue: 135, saturation: 94, lightness: 65, alpha: 1 },
      "chart-4": { hue: 191, saturation: 97, lightness: 77, alpha: 1 },
      "chart-5": { hue: 65, saturation: 92, lightness: 76, alpha: 1 },
      sidebar: { hue: 231, saturation: 15, lightness: 20, alpha: 1 },
      "sidebar-foreground": { hue: 60, saturation: 30, lightness: 96, alpha: 1 },
      "sidebar-primary": { hue: 265, saturation: 89, lightness: 78, alpha: 1 },
      "sidebar-primary-foreground": { hue: 0, saturation: 0, lightness: 0, alpha: 1 },
      "sidebar-accent": { hue: 232, saturation: 14, lightness: 27, alpha: 1 },
      "sidebar-accent-foreground": { hue: 60, saturation: 30, lightness: 96, alpha: 1 },
      "sidebar-border": { hue: 232, saturation: 14, lightness: 31, alpha: 0.15 },
      "sidebar-ring": { hue: 265, saturation: 89, lightness: 78, alpha: 1 },
    },
  },
  {
    id: "nord",
    name: "Nord",
    description: "",
    author: "Arctic Ice Studio",
    tags: ["dark", "blue", "minimal"],
    light: {
      background: { hue: 220, saturation: 16, lightness: 96, alpha: 1 },
      foreground: { hue: 220, saturation: 16, lightness: 22, alpha: 1 },
      primary: { hue: 213, saturation: 32, lightness: 52, alpha: 1 },
      "primary-foreground": { hue: 0, saturation: 0, lightness: 100, alpha: 1 },
      secondary: { hue: 179, saturation: 25, lightness: 65, alpha: 1 },
      "secondary-foreground": { hue: 0, saturation: 0, lightness: 0, alpha: 1 },
      accent: { hue: 193, saturation: 43, lightness: 67, alpha: 1 },
      "accent-foreground": { hue: 0, saturation: 0, lightness: 0, alpha: 1 },
      card: { hue: 220, saturation: 16, lightness: 92, alpha: 1 },
      "card-foreground": { hue: 220, saturation: 16, lightness: 22, alpha: 1 },
      popover: { hue: 220, saturation: 16, lightness: 96, alpha: 1 },
      "popover-foreground": { hue: 220, saturation: 16, lightness: 22, alpha: 1 },
      muted: { hue: 220, saturation: 16, lightness: 88, alpha: 1 },
      "muted-foreground": { hue: 220, saturation: 16, lightness: 46, alpha: 1 },
      destructive: { hue: 354, saturation: 42, lightness: 56, alpha: 1 },
      "destructive-foreground": { hue: 0, saturation: 0, lightness: 100, alpha: 1 },
      border: { hue: 220, saturation: 16, lightness: 82, alpha: 1 },
      input: { hue: 220, saturation: 16, lightness: 82, alpha: 1 },
      ring: { hue: 213, saturation: 32, lightness: 52, alpha: 1 },
      success: { hue: 92, saturation: 28, lightness: 65, alpha: 1 },
      "success-foreground": { hue: 0, saturation: 0, lightness: 0, alpha: 1 },
      warning: { hue: 40, saturation: 71, lightness: 73, alpha: 1 },
      "warning-foreground": { hue: 0, saturation: 0, lightness: 0, alpha: 1 },
      info: { hue: 193, saturation: 43, lightness: 67, alpha: 1 },
      "info-foreground": { hue: 0, saturation: 0, lightness: 0, alpha: 1 },
      "chart-1": { hue: 213, saturation: 32, lightness: 52, alpha: 1 },
      "chart-2": { hue: 179, saturation: 25, lightness: 65, alpha: 1 },
      "chart-3": { hue: 193, saturation: 43, lightness: 67, alpha: 1 },
      "chart-4": { hue: 92, saturation: 28, lightness: 65, alpha: 1 },
      "chart-5": { hue: 311, saturation: 20, lightness: 63, alpha: 1 },
      sidebar: { hue: 220, saturation: 16, lightness: 98, alpha: 1 },
      "sidebar-foreground": { hue: 220, saturation: 16, lightness: 22, alpha: 1 },
      "sidebar-primary": { hue: 213, saturation: 32, lightness: 52, alpha: 1 },
      "sidebar-primary-foreground": { hue: 0, saturation: 0, lightness: 100, alpha: 1 },
      "sidebar-accent": { hue: 220, saturation: 16, lightness: 94, alpha: 1 },
      "sidebar-accent-foreground": { hue: 220, saturation: 16, lightness: 22, alpha: 1 },
      "sidebar-border": { hue: 220, saturation: 16, lightness: 86, alpha: 1 },
      "sidebar-ring": { hue: 213, saturation: 32, lightness: 52, alpha: 1 },
    },
    dark: {
      background: { hue: 220, saturation: 16, lightness: 22, alpha: 1 },
      foreground: { hue: 218, saturation: 27, lightness: 94, alpha: 1 },
      primary: { hue: 213, saturation: 32, lightness: 52, alpha: 1 },
      "primary-foreground": { hue: 0, saturation: 0, lightness: 100, alpha: 1 },
      secondary: { hue: 179, saturation: 25, lightness: 65, alpha: 1 },
      "secondary-foreground": { hue: 0, saturation: 0, lightness: 0, alpha: 1 },
      accent: { hue: 193, saturation: 43, lightness: 67, alpha: 1 },
      "accent-foreground": { hue: 0, saturation: 0, lightness: 0, alpha: 1 },
      card: { hue: 220, saturation: 16, lightness: 18, alpha: 1 },
      "card-foreground": { hue: 218, saturation: 27, lightness: 94, alpha: 1 },
      popover: { hue: 220, saturation: 16, lightness: 22, alpha: 1 },
      "popover-foreground": { hue: 218, saturation: 27, lightness: 94, alpha: 1 },
      muted: { hue: 220, saturation: 17, lightness: 32, alpha: 1 },
      "muted-foreground": { hue: 218, saturation: 27, lightness: 66, alpha: 1 },
      destructive: { hue: 354, saturation: 42, lightness: 56, alpha: 1 },
      "destructive-foreground": { hue: 0, saturation: 0, lightness: 100, alpha: 1 },
      border: { hue: 220, saturation: 17, lightness: 32, alpha: 1 },
      input: { hue: 220, saturation: 17, lightness: 32, alpha: 1 },
      ring: { hue: 213, saturation: 32, lightness: 52, alpha: 1 },
      success: { hue: 92, saturation: 28, lightness: 65, alpha: 1 },
      "success-foreground": { hue: 0, saturation: 0, lightness: 0, alpha: 1 },
      warning: { hue: 40, saturation: 71, lightness: 73, alpha: 1 },
      "warning-foreground": { hue: 0, saturation: 0, lightness: 0, alpha: 1 },
      info: { hue: 193, saturation: 43, lightness: 67, alpha: 1 },
      "info-foreground": { hue: 0, saturation: 0, lightness: 0, alpha: 1 },
      "chart-1": { hue: 213, saturation: 32, lightness: 52, alpha: 1 },
      "chart-2": { hue: 179, saturation: 25, lightness: 65, alpha: 1 },
      "chart-3": { hue: 193, saturation: 43, lightness: 67, alpha: 1 },
      "chart-4": { hue: 92, saturation: 28, lightness: 65, alpha: 1 },
      "chart-5": { hue: 311, saturation: 20, lightness: 63, alpha: 1 },
      sidebar: { hue: 220, saturation: 16, lightness: 18, alpha: 1 },
      "sidebar-foreground": { hue: 218, saturation: 27, lightness: 94, alpha: 1 },
      "sidebar-primary": { hue: 213, saturation: 32, lightness: 52, alpha: 1 },
      "sidebar-primary-foreground": { hue: 0, saturation: 0, lightness: 100, alpha: 1 },
      "sidebar-accent": { hue: 220, saturation: 17, lightness: 28, alpha: 1 },
      "sidebar-accent-foreground": { hue: 218, saturation: 27, lightness: 94, alpha: 1 },
      "sidebar-border": { hue: 220, saturation: 17, lightness: 32, alpha: 0.2 },
      "sidebar-ring": { hue: 213, saturation: 32, lightness: 52, alpha: 1 },
    },
  },
  {
    id: "catppuccin-mocha",
    name: "Catppuccin Mocha",
    description: "",
    author: "Catppuccin",
    tags: ["dark", "pastel", "cozy"],
    light: {
      background: { hue: 240, saturation: 21, lightness: 15, alpha: 1 },
      foreground: { hue: 226, saturation: 64, lightness: 88, alpha: 1 },
      primary: { hue: 267, saturation: 84, lightness: 81, alpha: 1 },
      "primary-foreground": { hue: 0, saturation: 0, lightness: 0, alpha: 1 },
      secondary: { hue: 189, saturation: 71, lightness: 73, alpha: 1 },
      "secondary-foreground": { hue: 0, saturation: 0, lightness: 0, alpha: 1 },
      accent: { hue: 343, saturation: 81, lightness: 75, alpha: 1 },
      "accent-foreground": { hue: 0, saturation: 0, lightness: 0, alpha: 1 },
      card: { hue: 240, saturation: 23, lightness: 18, alpha: 1 },
      "card-foreground": { hue: 226, saturation: 64, lightness: 88, alpha: 1 },
      popover: { hue: 240, saturation: 21, lightness: 15, alpha: 1 },
      "popover-foreground": { hue: 226, saturation: 64, lightness: 88, alpha: 1 },
      muted: { hue: 240, saturation: 21, lightness: 27, alpha: 1 },
      "muted-foreground": { hue: 227, saturation: 35, lightness: 80, alpha: 1 },
      destructive: { hue: 0, saturation: 68, lightness: 71, alpha: 1 },
      "destructive-foreground": { hue: 0, saturation: 0, lightness: 0, alpha: 1 },
      border: { hue: 240, saturation: 21, lightness: 27, alpha: 1 },
      input: { hue: 240, saturation: 21, lightness: 27, alpha: 1 },
      ring: { hue: 267, saturation: 84, lightness: 81, alpha: 1 },
      success: { hue: 115, saturation: 54, lightness: 76, alpha: 1 },
      "success-foreground": { hue: 0, saturation: 0, lightness: 0, alpha: 1 },
      warning: { hue: 35, saturation: 77, lightness: 77, alpha: 1 },
      "warning-foreground": { hue: 0, saturation: 0, lightness: 0, alpha: 1 },
      info: { hue: 189, saturation: 71, lightness: 73, alpha: 1 },
      "info-foreground": { hue: 0, saturation: 0, lightness: 0, alpha: 1 },
      "chart-1": { hue: 267, saturation: 84, lightness: 81, alpha: 1 },
      "chart-2": { hue: 343, saturation: 81, lightness: 75, alpha: 1 },
      "chart-3": { hue: 189, saturation: 71, lightness: 73, alpha: 1 },
      "chart-4": { hue: 115, saturation: 54, lightness: 76, alpha: 1 },
      "chart-5": { hue: 35, saturation: 77, lightness: 77, alpha: 1 },
      sidebar: { hue: 240, saturation: 23, lightness: 18, alpha: 1 },
      "sidebar-foreground": { hue: 226, saturation: 64, lightness: 88, alpha: 1 },
      "sidebar-primary": { hue: 267, saturation: 84, lightness: 81, alpha: 1 },
      "sidebar-primary-foreground": { hue: 0, saturation: 0, lightness: 0, alpha: 1 },
      "sidebar-accent": { hue: 240, saturation: 21, lightness: 24, alpha: 1 },
      "sidebar-accent-foreground": { hue: 226, saturation: 64, lightness: 88, alpha: 1 },
      "sidebar-border": { hue: 240, saturation: 21, lightness: 27, alpha: 0.3 },
      "sidebar-ring": { hue: 267, saturation: 84, lightness: 81, alpha: 1 },
    },
    dark: {
      background: { hue: 240, saturation: 21, lightness: 15, alpha: 1 },
      foreground: { hue: 226, saturation: 64, lightness: 88, alpha: 1 },
      primary: { hue: 267, saturation: 84, lightness: 81, alpha: 1 },
      "primary-foreground": { hue: 0, saturation: 0, lightness: 0, alpha: 1 },
      secondary: { hue: 189, saturation: 71, lightness: 73, alpha: 1 },
      "secondary-foreground": { hue: 0, saturation: 0, lightness: 0, alpha: 1 },
      accent: { hue: 343, saturation: 81, lightness: 75, alpha: 1 },
      "accent-foreground": { hue: 0, saturation: 0, lightness: 0, alpha: 1 },
      card: { hue: 240, saturation: 23, lightness: 18, alpha: 1 },
      "card-foreground": { hue: 226, saturation: 64, lightness: 88, alpha: 1 },
      popover: { hue: 240, saturation: 21, lightness: 15, alpha: 1 },
      "popover-foreground": { hue: 226, saturation: 64, lightness: 88, alpha: 1 },
      muted: { hue: 240, saturation: 21, lightness: 27, alpha: 1 },
      "muted-foreground": { hue: 227, saturation: 35, lightness: 80, alpha: 1 },
      destructive: { hue: 0, saturation: 68, lightness: 71, alpha: 1 },
      "destructive-foreground": { hue: 0, saturation: 0, lightness: 0, alpha: 1 },
      border: { hue: 240, saturation: 21, lightness: 27, alpha: 1 },
      input: { hue: 240, saturation: 21, lightness: 27, alpha: 1 },
      ring: { hue: 267, saturation: 84, lightness: 81, alpha: 1 },
      success: { hue: 115, saturation: 54, lightness: 76, alpha: 1 },
      "success-foreground": { hue: 0, saturation: 0, lightness: 0, alpha: 1 },
      warning: { hue: 35, saturation: 77, lightness: 77, alpha: 1 },
      "warning-foreground": { hue: 0, saturation: 0, lightness: 0, alpha: 1 },
      info: { hue: 189, saturation: 71, lightness: 73, alpha: 1 },
      "info-foreground": { hue: 0, saturation: 0, lightness: 0, alpha: 1 },
      "chart-1": { hue: 267, saturation: 84, lightness: 81, alpha: 1 },
      "chart-2": { hue: 343, saturation: 81, lightness: 75, alpha: 1 },
      "chart-3": { hue: 189, saturation: 71, lightness: 73, alpha: 1 },
      "chart-4": { hue: 115, saturation: 54, lightness: 76, alpha: 1 },
      "chart-5": { hue: 35, saturation: 77, lightness: 77, alpha: 1 },
      sidebar: { hue: 240, saturation: 23, lightness: 18, alpha: 1 },
      "sidebar-foreground": { hue: 226, saturation: 64, lightness: 88, alpha: 1 },
      "sidebar-primary": { hue: 267, saturation: 84, lightness: 81, alpha: 1 },
      "sidebar-primary-foreground": { hue: 0, saturation: 0, lightness: 0, alpha: 1 },
      "sidebar-accent": { hue: 240, saturation: 21, lightness: 24, alpha: 1 },
      "sidebar-accent-foreground": { hue: 226, saturation: 64, lightness: 88, alpha: 1 },
      "sidebar-border": { hue: 240, saturation: 21, lightness: 27, alpha: 0.15 },
      "sidebar-ring": { hue: 267, saturation: 84, lightness: 81, alpha: 1 },
    },
  },
  {
    id: "tokyo-night",
    name: "Tokyo Night",
    description: "",
    tags: ["dark", "blue", "modern"],
    light: {
      background: { hue: 220, saturation: 15, lightness: 96, alpha: 1 },
      foreground: { hue: 220, saturation: 15, lightness: 15, alpha: 1 },
      primary: { hue: 200, saturation: 98, lightness: 39, alpha: 1 },
      "primary-foreground": { hue: 0, saturation: 0, lightness: 100, alpha: 1 },
      secondary: { hue: 276, saturation: 58, lightness: 58, alpha: 1 },
      "secondary-foreground": { hue: 0, saturation: 0, lightness: 100, alpha: 1 },
      accent: { hue: 349, saturation: 75, lightness: 52, alpha: 1 },
      "accent-foreground": { hue: 0, saturation: 0, lightness: 100, alpha: 1 },
      card: { hue: 220, saturation: 15, lightness: 92, alpha: 1 },
      "card-foreground": { hue: 220, saturation: 15, lightness: 15, alpha: 1 },
      popover: { hue: 220, saturation: 15, lightness: 96, alpha: 1 },
      "popover-foreground": { hue: 220, saturation: 15, lightness: 15, alpha: 1 },
      muted: { hue: 220, saturation: 15, lightness: 88, alpha: 1 },
      "muted-foreground": { hue: 220, saturation: 15, lightness: 45, alpha: 1 },
      destructive: { hue: 349, saturation: 75, lightness: 52, alpha: 1 },
      "destructive-foreground": { hue: 0, saturation: 0, lightness: 100, alpha: 1 },
      border: { hue: 220, saturation: 15, lightness: 82, alpha: 1 },
      input: { hue: 220, saturation: 15, lightness: 82, alpha: 1 },
      ring: { hue: 200, saturation: 98, lightness: 39, alpha: 1 },
      success: { hue: 158, saturation: 64, lightness: 52, alpha: 1 },
      "success-foreground": { hue: 0, saturation: 0, lightness: 100, alpha: 1 },
      warning: { hue: 32, saturation: 93, lightness: 66, alpha: 1 },
      "warning-foreground": { hue: 0, saturation: 0, lightness: 0, alpha: 1 },
      info: { hue: 200, saturation: 98, lightness: 39, alpha: 1 },
      "info-foreground": { hue: 0, saturation: 0, lightness: 100, alpha: 1 },
      "chart-1": { hue: 200, saturation: 98, lightness: 39, alpha: 1 },
      "chart-2": { hue: 276, saturation: 58, lightness: 58, alpha: 1 },
      "chart-3": { hue: 349, saturation: 75, lightness: 52, alpha: 1 },
      "chart-4": { hue: 158, saturation: 64, lightness: 52, alpha: 1 },
      "chart-5": { hue: 32, saturation: 93, lightness: 66, alpha: 1 },
      sidebar: { hue: 220, saturation: 15, lightness: 98, alpha: 1 },
      "sidebar-foreground": { hue: 220, saturation: 15, lightness: 15, alpha: 1 },
      "sidebar-primary": { hue: 200, saturation: 98, lightness: 39, alpha: 1 },
      "sidebar-primary-foreground": { hue: 0, saturation: 0, lightness: 100, alpha: 1 },
      "sidebar-accent": { hue: 220, saturation: 15, lightness: 94, alpha: 1 },
      "sidebar-accent-foreground": { hue: 220, saturation: 15, lightness: 15, alpha: 1 },
      "sidebar-border": { hue: 220, saturation: 15, lightness: 86, alpha: 1 },
      "sidebar-ring": { hue: 200, saturation: 98, lightness: 39, alpha: 1 },
    },
    dark: {
      background: { hue: 220, saturation: 13, lightness: 18, alpha: 1 },
      foreground: { hue: 220, saturation: 14, lightness: 93, alpha: 1 },
      primary: { hue: 200, saturation: 98, lightness: 39, alpha: 1 },
      "primary-foreground": { hue: 0, saturation: 0, lightness: 100, alpha: 1 },
      secondary: { hue: 276, saturation: 58, lightness: 58, alpha: 1 },
      "secondary-foreground": { hue: 0, saturation: 0, lightness: 100, alpha: 1 },
      accent: { hue: 349, saturation: 75, lightness: 52, alpha: 1 },
      "accent-foreground": { hue: 0, saturation: 0, lightness: 100, alpha: 1 },
      card: { hue: 220, saturation: 15, lightness: 21, alpha: 1 },
      "card-foreground": { hue: 220, saturation: 14, lightness: 93, alpha: 1 },
      popover: { hue: 220, saturation: 13, lightness: 18, alpha: 1 },
      "popover-foreground": { hue: 220, saturation: 14, lightness: 93, alpha: 1 },
      muted: { hue: 220, saturation: 14, lightness: 32, alpha: 1 },
      "muted-foreground": { hue: 220, saturation: 14, lightness: 66, alpha: 1 },
      destructive: { hue: 349, saturation: 75, lightness: 52, alpha: 1 },
      "destructive-foreground": { hue: 0, saturation: 0, lightness: 100, alpha: 1 },
      border: { hue: 220, saturation: 14, lightness: 32, alpha: 1 },
      input: { hue: 220, saturation: 14, lightness: 32, alpha: 1 },
      ring: { hue: 200, saturation: 98, lightness: 39, alpha: 1 },
      success: { hue: 158, saturation: 64, lightness: 52, alpha: 1 },
      "success-foreground": { hue: 0, saturation: 0, lightness: 100, alpha: 1 },
      warning: { hue: 32, saturation: 93, lightness: 66, alpha: 1 },
      "warning-foreground": { hue: 0, saturation: 0, lightness: 0, alpha: 1 },
      info: { hue: 200, saturation: 98, lightness: 39, alpha: 1 },
      "info-foreground": { hue: 0, saturation: 0, lightness: 100, alpha: 1 },
      "chart-1": { hue: 200, saturation: 98, lightness: 39, alpha: 1 },
      "chart-2": { hue: 276, saturation: 58, lightness: 58, alpha: 1 },
      "chart-3": { hue: 349, saturation: 75, lightness: 52, alpha: 1 },
      "chart-4": { hue: 158, saturation: 64, lightness: 52, alpha: 1 },
      "chart-5": { hue: 32, saturation: 93, lightness: 66, alpha: 1 },
      sidebar: { hue: 220, saturation: 15, lightness: 16, alpha: 1 },
      "sidebar-foreground": { hue: 220, saturation: 14, lightness: 93, alpha: 1 },
      "sidebar-primary": { hue: 200, saturation: 98, lightness: 39, alpha: 1 },
      "sidebar-primary-foreground": { hue: 0, saturation: 0, lightness: 100, alpha: 1 },
      "sidebar-accent": { hue: 220, saturation: 14, lightness: 28, alpha: 1 },
      "sidebar-accent-foreground": { hue: 220, saturation: 14, lightness: 93, alpha: 1 },
      "sidebar-border": { hue: 220, saturation: 14, lightness: 32, alpha: 0.2 },
      "sidebar-ring": { hue: 200, saturation: 98, lightness: 39, alpha: 1 },
    },
  },
  {
    id: "github-dark",
    name: "GitHub Dark",
    description: "",
    tags: ["dark", "minimal", "professional"],
    light: {
      background: { hue: 0, saturation: 0, lightness: 100, alpha: 1 },
      foreground: { hue: 210, saturation: 11, lightness: 15, alpha: 1 },
      primary: { hue: 212, saturation: 92, lightness: 43, alpha: 1 },
      "primary-foreground": { hue: 0, saturation: 0, lightness: 100, alpha: 1 },
      secondary: { hue: 210, saturation: 18, lightness: 87, alpha: 1 },
      "secondary-foreground": { hue: 210, saturation: 11, lightness: 15, alpha: 1 },
      accent: { hue: 212, saturation: 92, lightness: 43, alpha: 1 },
      "accent-foreground": { hue: 0, saturation: 0, lightness: 100, alpha: 1 },
      card: { hue: 210, saturation: 18, lightness: 97, alpha: 1 },
      "card-foreground": { hue: 210, saturation: 11, lightness: 15, alpha: 1 },
      popover: { hue: 0, saturation: 0, lightness: 100, alpha: 1 },
      "popover-foreground": { hue: 210, saturation: 11, lightness: 15, alpha: 1 },
      muted: { hue: 210, saturation: 18, lightness: 87, alpha: 1 },
      "muted-foreground": { hue: 215, saturation: 13, lightness: 35, alpha: 1 },
      destructive: { hue: 356, saturation: 72, lightness: 44, alpha: 1 },
      "destructive-foreground": { hue: 0, saturation: 0, lightness: 100, alpha: 1 },
      border: { hue: 210, saturation: 18, lightness: 87, alpha: 1 },
      input: { hue: 210, saturation: 18, lightness: 87, alpha: 1 },
      ring: { hue: 212, saturation: 92, lightness: 43, alpha: 1 },
      success: { hue: 137, saturation: 55, lightness: 36, alpha: 1 },
      "success-foreground": { hue: 0, saturation: 0, lightness: 100, alpha: 1 },
      warning: { hue: 29, saturation: 80, lightness: 44, alpha: 1 },
      "warning-foreground": { hue: 0, saturation: 0, lightness: 100, alpha: 1 },
      info: { hue: 212, saturation: 92, lightness: 43, alpha: 1 },
      "info-foreground": { hue: 0, saturation: 0, lightness: 100, alpha: 1 },
      "chart-1": { hue: 212, saturation: 92, lightness: 43, alpha: 1 },
      "chart-2": { hue: 271, saturation: 76, lightness: 53, alpha: 1 },
      "chart-3": { hue: 137, saturation: 55, lightness: 36, alpha: 1 },
      "chart-4": { hue: 356, saturation: 72, lightness: 44, alpha: 1 },
      "chart-5": { hue: 29, saturation: 80, lightness: 44, alpha: 1 },
      sidebar: { hue: 210, saturation: 18, lightness: 99, alpha: 1 },
      "sidebar-foreground": { hue: 210, saturation: 11, lightness: 15, alpha: 1 },
      "sidebar-primary": { hue: 212, saturation: 92, lightness: 43, alpha: 1 },
      "sidebar-primary-foreground": { hue: 0, saturation: 0, lightness: 100, alpha: 1 },
      "sidebar-accent": { hue: 210, saturation: 18, lightness: 93, alpha: 1 },
      "sidebar-accent-foreground": { hue: 210, saturation: 11, lightness: 15, alpha: 1 },
      "sidebar-border": { hue: 210, saturation: 18, lightness: 90, alpha: 1 },
      "sidebar-ring": { hue: 212, saturation: 92, lightness: 43, alpha: 1 },
    },
    dark: {
      background: { hue: 220, saturation: 13, lightness: 9, alpha: 1 },
      foreground: { hue: 213, saturation: 10, lightness: 88, alpha: 1 },
      primary: { hue: 212, saturation: 92, lightness: 45, alpha: 1 },
      "primary-foreground": { hue: 0, saturation: 0, lightness: 0, alpha: 1 },
      secondary: { hue: 215, saturation: 14, lightness: 20, alpha: 1 },
      "secondary-foreground": { hue: 213, saturation: 10, lightness: 88, alpha: 1 },
      accent: { hue: 212, saturation: 92, lightness: 45, alpha: 1 },
      "accent-foreground": { hue: 0, saturation: 0, lightness: 0, alpha: 1 },
      card: { hue: 215, saturation: 14, lightness: 13, alpha: 1 },
      "card-foreground": { hue: 213, saturation: 10, lightness: 88, alpha: 1 },
      popover: { hue: 220, saturation: 13, lightness: 9, alpha: 1 },
      "popover-foreground": { hue: 213, saturation: 10, lightness: 88, alpha: 1 },
      muted: { hue: 215, saturation: 14, lightness: 20, alpha: 1 },
      "muted-foreground": { hue: 217, saturation: 10, lightness: 65, alpha: 1 },
      destructive: { hue: 4, saturation: 90, lightness: 58, alpha: 1 },
      "destructive-foreground": { hue: 0, saturation: 0, lightness: 0, alpha: 1 },
      border: { hue: 215, saturation: 14, lightness: 20, alpha: 1 },
      input: { hue: 215, saturation: 14, lightness: 20, alpha: 1 },
      ring: { hue: 212, saturation: 92, lightness: 45, alpha: 1 },
      success: { hue: 142, saturation: 70, lightness: 45, alpha: 1 },
      "success-foreground": { hue: 0, saturation: 0, lightness: 0, alpha: 1 },
      warning: { hue: 41, saturation: 96, lightness: 57, alpha: 1 },
      "warning-foreground": { hue: 0, saturation: 0, lightness: 0, alpha: 1 },
      info: { hue: 212, saturation: 92, lightness: 45, alpha: 1 },
      "info-foreground": { hue: 0, saturation: 0, lightness: 0, alpha: 1 },
      "chart-1": { hue: 212, saturation: 92, lightness: 45, alpha: 1 },
      "chart-2": { hue: 271, saturation: 76, lightness: 53, alpha: 1 },
      "chart-3": { hue: 142, saturation: 70, lightness: 45, alpha: 1 },
      "chart-4": { hue: 4, saturation: 90, lightness: 58, alpha: 1 },
      "chart-5": { hue: 41, saturation: 96, lightness: 57, alpha: 1 },
      sidebar: { hue: 215, saturation: 14, lightness: 11, alpha: 1 },
      "sidebar-foreground": { hue: 213, saturation: 10, lightness: 88, alpha: 1 },
      "sidebar-primary": { hue: 212, saturation: 92, lightness: 45, alpha: 1 },
      "sidebar-primary-foreground": { hue: 0, saturation: 0, lightness: 0, alpha: 1 },
      "sidebar-accent": { hue: 215, saturation: 14, lightness: 18, alpha: 1 },
      "sidebar-accent-foreground": { hue: 213, saturation: 10, lightness: 88, alpha: 1 },
      "sidebar-border": { hue: 215, saturation: 14, lightness: 20, alpha: 0.2 },
      "sidebar-ring": { hue: 212, saturation: 92, lightness: 45, alpha: 1 },
    },
  },
  {
    id: "solarized",
    name: "Solarized Dark",
    description: "",
    author: "Ethan Schoonover",
    tags: ["dark", "warm", "classic"],
    light: {
      background: { hue: 44, saturation: 87, lightness: 94, alpha: 1 },
      foreground: { hue: 192, saturation: 81, lightness: 14, alpha: 1 },
      primary: { hue: 205, saturation: 69, lightness: 49, alpha: 1 },
      "primary-foreground": { hue: 0, saturation: 0, lightness: 100, alpha: 1 },
      secondary: { hue: 68, saturation: 100, lightness: 30, alpha: 1 },
      "secondary-foreground": { hue: 0, saturation: 0, lightness: 100, alpha: 1 },
      accent: { hue: 237, saturation: 45, lightness: 77, alpha: 1 },
      "accent-foreground": { hue: 0, saturation: 0, lightness: 0, alpha: 1 },
      card: { hue: 45, saturation: 100, lightness: 96, alpha: 1 },
      "card-foreground": { hue: 192, saturation: 81, lightness: 14, alpha: 1 },
      popover: { hue: 44, saturation: 87, lightness: 94, alpha: 1 },
      "popover-foreground": { hue: 192, saturation: 81, lightness: 14, alpha: 1 },
      muted: { hue: 45, saturation: 100, lightness: 92, alpha: 1 },
      "muted-foreground": { hue: 186, saturation: 13, lightness: 47, alpha: 1 },
      destructive: { hue: 1, saturation: 79, lightness: 55, alpha: 1 },
      "destructive-foreground": { hue: 0, saturation: 0, lightness: 100, alpha: 1 },
      border: { hue: 45, saturation: 100, lightness: 92, alpha: 1 },
      input: { hue: 45, saturation: 100, lightness: 92, alpha: 1 },
      ring: { hue: 205, saturation: 69, lightness: 49, alpha: 1 },
      success: { hue: 68, saturation: 100, lightness: 30, alpha: 1 },
      "success-foreground": { hue: 0, saturation: 0, lightness: 100, alpha: 1 },
      warning: { hue: 18, saturation: 89, lightness: 55, alpha: 1 },
      "warning-foreground": { hue: 0, saturation: 0, lightness: 100, alpha: 1 },
      info: { hue: 205, saturation: 69, lightness: 49, alpha: 1 },
      "info-foreground": { hue: 0, saturation: 0, lightness: 100, alpha: 1 },
      "chart-1": { hue: 205, saturation: 69, lightness: 49, alpha: 1 },
      "chart-2": { hue: 175, saturation: 59, lightness: 40, alpha: 1 },
      "chart-3": { hue: 68, saturation: 100, lightness: 30, alpha: 1 },
      "chart-4": { hue: 237, saturation: 45, lightness: 77, alpha: 1 },
      "chart-5": { hue: 1, saturation: 79, lightness: 55, alpha: 1 },
      sidebar: { hue: 45, saturation: 100, lightness: 97, alpha: 1 },
      "sidebar-foreground": { hue: 192, saturation: 81, lightness: 14, alpha: 1 },
      "sidebar-primary": { hue: 205, saturation: 69, lightness: 49, alpha: 1 },
      "sidebar-primary-foreground": { hue: 0, saturation: 0, lightness: 100, alpha: 1 },
      "sidebar-accent": { hue: 45, saturation: 100, lightness: 93, alpha: 1 },
      "sidebar-accent-foreground": { hue: 192, saturation: 81, lightness: 14, alpha: 1 },
      "sidebar-border": { hue: 45, saturation: 100, lightness: 88, alpha: 1 },
      "sidebar-ring": { hue: 205, saturation: 69, lightness: 49, alpha: 1 },
    },
    dark: {
      background: { hue: 192, saturation: 100, lightness: 11, alpha: 1 },
      foreground: { hue: 44, saturation: 87, lightness: 94, alpha: 1 },
      primary: { hue: 205, saturation: 69, lightness: 49, alpha: 1 },
      "primary-foreground": { hue: 0, saturation: 0, lightness: 100, alpha: 1 },
      secondary: { hue: 68, saturation: 100, lightness: 30, alpha: 1 },
      "secondary-foreground": { hue: 0, saturation: 0, lightness: 100, alpha: 1 },
      accent: { hue: 237, saturation: 45, lightness: 77, alpha: 1 },
      "accent-foreground": { hue: 0, saturation: 0, lightness: 0, alpha: 1 },
      card: { hue: 192, saturation: 100, lightness: 14, alpha: 1 },
      "card-foreground": { hue: 44, saturation: 87, lightness: 94, alpha: 1 },
      popover: { hue: 192, saturation: 100, lightness: 11, alpha: 1 },
      "popover-foreground": { hue: 44, saturation: 87, lightness: 94, alpha: 1 },
      muted: { hue: 193, saturation: 100, lightness: 18, alpha: 1 },
      "muted-foreground": { hue: 186, saturation: 8, lightness: 55, alpha: 1 },
      destructive: { hue: 1, saturation: 79, lightness: 55, alpha: 1 },
      "destructive-foreground": { hue: 0, saturation: 0, lightness: 100, alpha: 1 },
      border: { hue: 193, saturation: 100, lightness: 18, alpha: 1 },
      input: { hue: 193, saturation: 100, lightness: 18, alpha: 1 },
      ring: { hue: 205, saturation: 69, lightness: 49, alpha: 1 },
      success: { hue: 68, saturation: 100, lightness: 30, alpha: 1 },
      "success-foreground": { hue: 0, saturation: 0, lightness: 100, alpha: 1 },
      warning: { hue: 18, saturation: 89, lightness: 55, alpha: 1 },
      "warning-foreground": { hue: 0, saturation: 0, lightness: 100, alpha: 1 },
      info: { hue: 205, saturation: 69, lightness: 49, alpha: 1 },
      "info-foreground": { hue: 0, saturation: 0, lightness: 100, alpha: 1 },
      "chart-1": { hue: 205, saturation: 69, lightness: 49, alpha: 1 },
      "chart-2": { hue: 175, saturation: 59, lightness: 40, alpha: 1 },
      "chart-3": { hue: 68, saturation: 100, lightness: 30, alpha: 1 },
      "chart-4": { hue: 237, saturation: 45, lightness: 77, alpha: 1 },
      "chart-5": { hue: 1, saturation: 79, lightness: 55, alpha: 1 },
      sidebar: { hue: 192, saturation: 100, lightness: 13, alpha: 1 },
      "sidebar-foreground": { hue: 44, saturation: 87, lightness: 94, alpha: 1 },
      "sidebar-primary": { hue: 205, saturation: 69, lightness: 49, alpha: 1 },
      "sidebar-primary-foreground": { hue: 0, saturation: 0, lightness: 100, alpha: 1 },
      "sidebar-accent": { hue: 193, saturation: 100, lightness: 16, alpha: 1 },
      "sidebar-accent-foreground": { hue: 44, saturation: 87, lightness: 94, alpha: 1 },
      "sidebar-border": { hue: 193, saturation: 100, lightness: 18, alpha: 0.2 },
      "sidebar-ring": { hue: 205, saturation: 69, lightness: 49, alpha: 1 },
    },
  },
];

/**
 * Get preset by ID
 */
export function getPresetById(id: string): ThemePreset | undefined {
  return themePresets.find((preset) => preset.id === id);
}

/**
 * Get presets by tag
 */
export function getPresetsByTag(tag: string): ThemePreset[] {
  return themePresets.filter((preset) => preset.tags.includes(tag));
}

/**
 * Get all unique tags
 */
export function getAllTags(): string[] {
  const tags = new Set<string>();
  themePresets.forEach((preset) => {
    preset.tags.forEach((tag) => tags.add(tag));
  });
  return Array.from(tags).sort();
}
